server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /gwr {
        alias /usr/share/nginx/html/gwr;
        try_files $uri $uri/ /gwr/index.html;
    }

    location /gto {
        alias /usr/share/nginx/html/gto;
        try_files $uri $uri/ /gto/index.html;
    }
}
